import { ROLES, type UserRole } from './roles.js';

export const PERMISSIONS = {
  // Members
  MEMBERS_VIEW: 'members.view',
  MEMBERS_CREATE: 'members.create',
  MEMBERS_UPDATE: 'members.update',
  MEMBERS_DELETE: 'members.delete',

  // Families
  FAMILIES_VIEW: 'families.view',
  FAMILIES_CREATE: 'families.create',
  FAMILIES_UPDATE: 'families.update',
  FAMILIES_DELETE: 'families.delete',
  FAMILIES_MANAGE_MEMBERS: 'families.manage_members',
  FAMILIES_APPROVE_REQUESTS: 'families.approve_requests',

  // Finance & Payments
  FINANCE_VIEW: 'finance.view',
  FINANCE_CREATE_PAYMENT: 'finance.create_payment',
  FINANCE_VERIFY_PAYMENT: 'finance.verify_payment',
  FINANCE_CREATE_EXPENSE: 'finance.create_expense',
  FINANCE_VIEW_REPORTS: 'finance.view_reports',

  // Applications
  APPLICATIONS_VIEW: 'applications.view',
  APPLICATIONS_CREATE: 'applications.create',
  APPLICATIONS_REVIEW: 'applications.review',
  APPLICATIONS_APPROVE: 'applications.approve',
  APPLICATIONS_REJECT: 'applications.reject',
  APPLICATIONS_COMPLETE: 'applications.complete',

  // Welfare & Zakat
  WELFARE_VIEW: 'welfare.view',
  WELFARE_MANAGE: 'welfare.manage',
  WELFARE_DISTRIBUTE: 'welfare.distribute',

  // Users & Roles
  USERS_VIEW: 'users.view',
  USERS_UPDATE_ROLE: 'users.update_role',
  USERS_UPDATE_STATUS: 'users.update_status',

  // Events & Volunteers
  EVENTS_VIEW: 'events.view',
  EVENTS_MANAGE: 'events.manage',
  VOLUNTEERS_MANAGE: 'volunteers.manage',

  // Madrasa
  MADRASA_MANAGE: 'madrasa.manage',
  MADRASA_ATTENDANCE: 'madrasa.attendance',
  MADRASA_GRADES: 'madrasa.grades',

  // Mosque & Services
  MOSQUE_MANAGE: 'mosque.manage',
  FUNERAL_MANAGE: 'funeral.manage',
  MARRIAGE_MANAGE: 'marriage.manage',

  // Assets & Committee
  ASSETS_MANAGE: 'assets.manage',
  COMMITTEE_MANAGE: 'committee.manage',

  // Announcements & Notifications
  ANNOUNCEMENTS_MANAGE: 'announcements.manage',

  // Hajj & Umrah
  HAJJ_UMRAH_VIEW: 'hajj_umrah.view',
  HAJJ_UMRAH_MANAGE: 'hajj_umrah.manage',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS) as Permission[],

  [ROLES.SECRETARY]: [
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.MEMBERS_CREATE,
    PERMISSIONS.MEMBERS_UPDATE,
    PERMISSIONS.FAMILIES_VIEW,
    PERMISSIONS.FAMILIES_CREATE,
    PERMISSIONS.FAMILIES_UPDATE,
    PERMISSIONS.FAMILIES_DELETE,
    PERMISSIONS.FAMILIES_MANAGE_MEMBERS,
    PERMISSIONS.FAMILIES_APPROVE_REQUESTS,
    PERMISSIONS.APPLICATIONS_VIEW,
    PERMISSIONS.APPLICATIONS_REVIEW,
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.EVENTS_MANAGE,
    PERMISSIONS.VOLUNTEERS_MANAGE,
    PERMISSIONS.COMMITTEE_MANAGE,
    PERMISSIONS.ANNOUNCEMENTS_MANAGE,
    PERMISSIONS.FUNERAL_MANAGE,
    PERMISSIONS.MARRIAGE_MANAGE,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.HAJJ_UMRAH_VIEW,
    PERMISSIONS.HAJJ_UMRAH_MANAGE,
    PERMISSIONS.MADRASA_MANAGE,
    PERMISSIONS.MADRASA_ATTENDANCE,
    PERMISSIONS.MADRASA_GRADES,
  ],

  [ROLES.TREASURER]: [
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_CREATE_PAYMENT,
    PERMISSIONS.FINANCE_VERIFY_PAYMENT,
    PERMISSIONS.FINANCE_CREATE_EXPENSE,
    PERMISSIONS.FINANCE_VIEW_REPORTS,
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.FAMILIES_VIEW,
    PERMISSIONS.APPLICATIONS_VIEW,
    PERMISSIONS.ASSETS_MANAGE,
    PERMISSIONS.HAJJ_UMRAH_VIEW,
  ],

  [ROLES.IMAM]: [
    PERMISSIONS.MOSQUE_MANAGE,
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.ANNOUNCEMENTS_MANAGE,
    PERMISSIONS.FUNERAL_MANAGE,
    PERMISSIONS.MARRIAGE_MANAGE,
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.HAJJ_UMRAH_VIEW,
  ],

  [ROLES.MADRASA_ADMIN]: [
    PERMISSIONS.MADRASA_MANAGE,
    PERMISSIONS.MADRASA_ATTENDANCE,
    PERMISSIONS.MADRASA_GRADES,
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.FAMILIES_VIEW,
  ],

  [ROLES.WELFARE_OFFICER]: [
    PERMISSIONS.WELFARE_VIEW,
    PERMISSIONS.WELFARE_MANAGE,
    PERMISSIONS.WELFARE_DISTRIBUTE,
    PERMISSIONS.APPLICATIONS_VIEW,
    PERMISSIONS.APPLICATIONS_REVIEW,
    PERMISSIONS.APPLICATIONS_APPROVE,
    PERMISSIONS.APPLICATIONS_REJECT,
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.FAMILIES_VIEW,
  ],

  [ROLES.COMMITTEE_MEMBER]: [
    PERMISSIONS.COMMITTEE_MANAGE,
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.FAMILIES_VIEW,
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.HAJJ_UMRAH_VIEW,
  ],

  [ROLES.FAMILY_HEAD]: [
    PERMISSIONS.APPLICATIONS_CREATE,
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.HAJJ_UMRAH_VIEW,
  ],

  [ROLES.VOLUNTEER]: [
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.HAJJ_UMRAH_VIEW,
  ],

  [ROLES.MEMBER]: [
    PERMISSIONS.APPLICATIONS_CREATE,
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.HAJJ_UMRAH_VIEW,
  ],
};
