export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  SECRETARY: 'SECRETARY',
  TREASURER: 'TREASURER',
  IMAM: 'IMAM',
  MADRASA_ADMIN: 'MADRASA_ADMIN',
  WELFARE_OFFICER: 'WELFARE_OFFICER',
  COMMITTEE_MEMBER: 'COMMITTEE_MEMBER',
  FAMILY_HEAD: 'FAMILY_HEAD',
  VOLUNTEER: 'VOLUNTEER',
  MEMBER: 'MEMBER',
} as const;

export type UserRole = (typeof ROLES)[keyof typeof ROLES];

export const ALL_ROLES = Object.values(ROLES) as UserRole[];

export const PRIVILEGED_ROLES: UserRole[] = [
  ROLES.SUPER_ADMIN,
  ROLES.SECRETARY,
  ROLES.TREASURER,
  ROLES.IMAM,
  ROLES.MADRASA_ADMIN,
  ROLES.WELFARE_OFFICER,
  ROLES.COMMITTEE_MEMBER,
];
